# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Katy Scott
author_email: joshuasiraj@gmail.com
author_full_name: Joshua Siraj
github_username: JoshuaSiraj
has_additional_authors: true
project_description: ''
project_name: AAuRA Benchmark Testing
project_slug: ab-testing
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
