[workspace]
authors = ["Joshua Siraj <joshua.siraj@ryerson.ca>"]
channels = ["conda-forge"]
name = "ab_testing"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
# convenient variables which can be used in scripts
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.METADATA = "${PIXI_PROJECT_ROOT}/metadata"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"

[dependencies]
python = ">=3.11,<3.14"
simpleitk = ">=2.5.5,<3"

[pypi-dependencies]
pydantic = ">=2.13.4, <3"
damply = ">=0.26.1, <0.27"
med-imagetools = ">=2.15.0"